export const productMovies = [
  {
    id: 1,
    title: 'Pickle, The',
    price: '$58.94',
    img: 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/yCzdS1R27F675iSUIfOHQKxFpiB.jpg',
    quantity: 0,
    inStock: false,
    producer: 'Warner Bros. Pictures',
    color: '#9e091a',
    genre: 'Comedy',
  },
  {
    id: 2,
    title: 'American Splendor',
    price: '$15.40',
    img: 'https://m.media-amazon.com/images/M/MV5BMjA0MjYxNjY1MV5BMl5BanBnXkFtZTcwNDkwMjAwMQ@@._V1_QL75_UX100_CR0,0,100,148_.jpg',
    quantity: 50,
    inStock: true,
    producer: 'Sony Pictures Classics',
    color: '#2005b6',
    genre: 'Comedy|Drama',
  },
  {
    id: 3,
    title: 'Oak, The (Balanta)',
    price: '$61.22',
    img: 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/7eNbNHfsm7SvyFb8LTzsCQ5WiMK.jpg',
    quantity: 151,
    inStock: true,
    producer: 'Universal Pictures',
    color: '#2ff11b',
    genre: 'Comedy|Drama',
  },
  {
    id: 4,
    title: "Endurance: Shackleton's Legendary Antarctic Expedition, The",
    price: '$11.12',
    img: 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/7zWvRlfnDTbmcGw8F28PEx7KX2k.jpg',
    quantity: 92,
    inStock: true,
    producer: 'National Geographic',
    color: '#8e90b6',
    genre: 'Documentary',
  },
  {
    id: 5,
    title: "Love's Enduring Promise",
    price: '$88.87',
    img: 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/lwbeyOtRpn1izaRnVVhDSJGwHRu.jpg',
    quantity: 106,
    inStock: true,
    producer: '20th Century Studios',
    color: '#b39637',
    genre: 'Drama|Romance',
  },
  {
    id: 6,
    title: 'Attila (Attila the Hun)',
    price: '$60.53',
    img: 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/6ALZ8TuhPUvx7gpuKuyD1dNfYI3.jpg',
    quantity: 99,
    inStock: true,
    producer: 'Paramount Pictures',
    color: '#79b794',
    genre: 'Action|Adventure|Drama|War',
  },
  {
    id: 7,
    title: 'Hi Tessa (Czesc Tereska)',
    price: '$12.96',
    img: 'insertImgHere',
    quantity: 33,
    inStock: true,
    producer: 'Lionsgate',
    color: '#793a88',
    genre: 'Drama',
  },
  {
    id: 8,
    title: 'Da Vinci Code, The',
    price: '$30.99',
    img: 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/j9lsWwnIDN2ZNtqZcE1x2o4ZKyI.jpg',
    quantity: 140,
    inStock: true,
    producer: 'Columbia Pictures',
    color: '#42d8d3',
    genre: 'Drama|Mystery|Thriller',
  },
  {
    id: 9,
    title: 'When Ladies Meet',
    price: '$64.75',
    img: 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/6GGK7UGIT1mG8wbGiDouhG9joaO.jpg',
    quantity: 0,
    inStock: false,
    producer: 'Walt Disney Pictures',
    color: '#633acb',
    genre: 'Comedy|Drama|Romance',
  },
  {
    id: 10,
    title:
      'Children Who Chase Lost Voices from Deep Below (Hoshi o ou kodomo) (Journey to Agartha)',
    price: '$70.76',
    img: 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/lH9VeRriF8tGakDteReYy71iVGK.jpg',
    quantity: 123,
    inStock: true,
    producer: 'Studio Ghibli',
    color: '#edc104',
    genre: 'Animation|Drama|Fantasy',
  },
  {
    id: 11,
    title: 'Old Men in New Cars (Gamle mænd i nye biler)',
    price: '$56.76',
    img: 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/n2KH5TlEcYPvinmwsJj4ULc1xDO.jpg',
    quantity: 136,
    inStock: true,
    producer: 'DreamWorks Pictures',
    color: '#d84958',
    genre: 'Action|Comedy',
  },
  {
    id: 12,
    title: 'Last Chance Harvey',
    price: '$65.01',
    img: 'insertImgHere',
    quantity: 50,
    inStock: true,
    producer: 'Focus Features',
    color: '#87dea4',
    genre: 'Drama|Romance',
  },
  {
    id: 13,
    title: 'Trilogy of Terror',
    price: '$93.11',
    img: 'insertImgHere',
    quantity: 140,
    inStock: true,
    producer: 'Universal Pictures',
    color: '#91c473',
    genre: 'Horror|Thriller',
  },
  {
    id: 14,
    title: '12 Angry Men',
    price: '$46.22',
    img: 'insertImgHere',
    quantity: 90,
    inStock: true,
    producer: 'MGM Studios',
    color: '#6f6316',
    genre: 'Drama',
  },
  {
    id: 15,
    title: 'Wszystko, co kocham',
    price: '$64.85',
    img: 'insertImgHere',
    quantity: 152,
    inStock: true,
    producer: 'Universal Pictures',
    color: '#497e67',
    genre: 'Comedy|Drama',
  },
  {
    id: 16,
    title: 'Hideous Kinky',
    price: '$46.36',
    img: 'insertImgHere',
    quantity: 106,
    inStock: true,
    producer: 'BBC Films',
    color: '#d706be',
    genre: 'Drama',
  },
  {
    id: 17,
    title: 'Unlikely Weapon, An',
    price: '$45.91',
    img: 'insertImgHere',
    quantity: 137,
    inStock: true,
    producer: 'Magnolia Pictures',
    color: '#ab6064',
    genre: 'Documentary',
  },
  {
    id: 18,
    title: 'Big Fix, The',
    price: '$52.03',
    img: 'insertImgHere',
    quantity: 22,
    inStock: true,
    producer: 'Lionsgate',
    color: '#45faf7',
    genre: 'Comedy|Mystery|Thriller',
  },
  {
    id: 19,
    title: "Madonna's Pig",
    price: '$88.99',
    img: 'insertImgHere',
    quantity: 155,
    inStock: true,
    producer: '20th Century Studios',
    color: '#71954b',
    genre: 'Fantasy|Romance|Sci-Fi',
  },
  {
    id: 20,
    title: 'Orders to Kill',
    price: '$41.47',
    img: 'insertImgHere',
    quantity: 0,
    inStock: false,
    producer: 'Warner Bros. Pictures',
    color: '#ee7e44',
    genre: 'Drama|War',
  },
];