export const teamSales = [
  {
    id: 1,
    firstName: 'Pierce',
    lastName: 'Frost',
    email: 'pfrost0@digg.com',
    salesTotal: '$12418.99',
    img: 'https://randomuser.me/api/portraits/men/2.jpg',
    verified: true,
    phoneNumber: '(123) 456-7890',
  },
  {
    id: 2,
    firstName: 'Maddi',
    lastName: 'Minget',
    email: 'mminget1@woothemes.com',
    salesTotal: '$9040.21',
    img: 'https://randomuser.me/api/portraits/women/67.jpg',
    verified: false,
    phoneNumber: '(234) 567-8901',
  },
  {
    id: 3,
    firstName: 'Molly',
    lastName: 'Lardeur',
    email: 'mlardeur2@ameblo.jp',
    salesTotal: '$9352.91',
    img: 'https://randomuser.me/api/portraits/women/66.jpg',
    verified: true,
    phoneNumber: '(345) 678-9012',
  },
  {
    id: 4,
    firstName: 'Tedmund',
    lastName: 'Haszard',
    email: 'thaszard3@i2i.jp',
    salesTotal: '$8279.61',
    img: 'https://randomuser.me/api/portraits/men/17.jpg',
    verified: false,
    phoneNumber: '(456) 789-0123',
  },
  {
    id: 5,
    firstName: 'Modesty',
    lastName: 'Drewe',
    email: 'mdrewe4@cornell.edu',
    salesTotal: '$11320.87',
    img: 'https://randomuser.me/api/portraits/women/23.jpg',
    verified: true,
    phoneNumber: '(567) 890-1234',
  },
  {
    id: 6,
    firstName: 'Paola',
    lastName: 'Paprotny',
    email: 'ppaprotny5@dropbox.com',
    salesTotal: '$12773.66',
    img: 'https://randomuser.me/api/portraits/women/70.jpg',
    verified: false,
    phoneNumber: '(678) 901-2345',
  },
  {
    id: 7,
    firstName: 'Emery',
    lastName: 'Ornelas',
    email: 'eornelas6@comsenz.com',
    salesTotal: '$9307.01',
    img: 'https://randomuser.me/api/portraits/men/87.jpg',
    verified: true,
    phoneNumber: '(789) 012-3456',
  },
  {
    id: 8,
    firstName: 'Fifi',
    lastName: 'Brookzie',
    email: 'fbrookzie7@ning.com',
    salesTotal: '$5998.81',
    img: 'https://randomuser.me/api/portraits/women/1.jpg',
    verified: false,
    phoneNumber: '(890) 123-4567',
  },
  {
    id: 9,
    firstName: 'Philly',
    lastName: "O'Shiels",
    email: 'poshiels8@yahoo.co.jp',
    salesTotal: '$7417.51',
    img: 'https://randomuser.me/api/portraits/men/67.jpg',
    verified: true,
    phoneNumber: '(901) 234-5678',
  },
  {
    id: 10,
    firstName: 'Tally',
    lastName: 'Tanton',
    email: 'ttanton9@weather.com',
    salesTotal: '$7233.64',
    img: 'https://randomuser.me/api/portraits/women/57.jpg',
    verified: false,
    phoneNumber: '(012) 345-6789',
  },
  {
    id: 11,
    firstName: 'Raquela',
    lastName: 'Napier',
    email: 'rnapiera@youtube.com',
    salesTotal: '$10480.21',
    img: 'https://randomuser.me/api/portraits/women/92.jpg',
    verified: true,
    phoneNumber: '(123) 456-7890',
  },
  {
    id: 12,
    firstName: 'Tish',
    lastName: 'Gadie',
    email: 'tgadieb@goo.gl',
    salesTotal: '$11750.50',
    img: 'https://randomuser.me/api/portraits/women/0.jpg',
    verified: false,
    phoneNumber: '(234) 567-8901',
  },
  {
    id: 13,
    firstName: 'Major',
    lastName: 'Bateman',
    email: 'mbatemanc@usgs.gov',
    salesTotal: '$8785.94',
    img: 'https://randomuser.me/api/portraits/men/5.jpg',
    verified: true,
    phoneNumber: '(345) 678-9012',
  },
  {
    id: 14,
    firstName: 'Sherwood',
    lastName: 'Huckfield',
    email: 'shuckfieldd@goo.gl',
    salesTotal: '$13199.99',
    img: 'https://randomuser.me/api/portraits/men/79.jpg',
    verified: false,
    phoneNumber: '(456) 789-0123',
  },
  {
    id: 15,
    firstName: 'Allyn',
    lastName: 'Rodda',
    email: 'aroddae@yahoo.co.jp',
    salesTotal: '$5849.82',
    img: 'https://randomuser.me/api/portraits/men/18.jpg',
    verified: true,
    phoneNumber: '(567) 890-1234',
  },
  {
    id: 16,
    firstName: 'Ardyce',
    lastName: 'Oliveira',
    email: 'aoliveiraf@google.com.br',
    salesTotal: '$7227.12',
    img: 'https://randomuser.me/api/portraits/men/94.jpg',
    verified: false,
    phoneNumber: '(678) 901-2345',
  },
  {
    id: 17,
    firstName: 'Timothy',
    lastName: 'Weeds',
    email: 'tweedsg@engadget.com',
    salesTotal: '$10279.10',
    img: 'https://randomuser.me/api/portraits/men/88.jpg',
    verified: true,
    phoneNumber: '(789) 012-3456',
  },
  {
    id: 18,
    firstName: 'Dodi',
    lastName: 'Roake',
    email: 'droakeh@example.com',
    salesTotal: '$6895.49',
    img: 'https://randomuser.me/api/portraits/women/28.jpg',
    verified: false,
    phoneNumber: '(890) 123-4567',
  },
  {
    id: 19,
    firstName: 'Corissa',
    lastName: 'Jewiss',
    email: 'cjewissi@deliciousdays.com',
    salesTotal: '$9625.36',
    img: 'https://xsgames.co/randomusers/assets/avatars/female/5.jpg',
    verified: true,
    phoneNumber: '(901) 234-5678',
  },
  {
    id: 20,
    firstName: 'Ivette',
    lastName: 'Ninnis',
    email: 'ininnisj@ed.gov',
    salesTotal: '$7176.32',
    img: 'https://randomuser.me/api/portraits/women/29.jpg',
    verified: false,
    phoneNumber: '(012) 345-6789',
  },
  {
    id: 21,
    firstName: 'Verney',
    lastName: 'Getch',
    email: 'vgetchk@mlb.com',
    salesTotal: '$6357.56',
    img: 'https://randomuser.me/api/portraits/men/60.jpg',
    verified: true,
    phoneNumber: '(123) 456-7890',
  },
  {
    id: 22,
    firstName: 'Violette',
    lastName: 'Thomasset',
    email: 'vthomassetl@wsj.com',
    salesTotal: '$5855.07',
    img: 'https://randomuser.me/api/portraits/women/24.jpg',
    verified: true,
    phoneNumber: '(234) 567-8901',
  },
  {
    id: 23,
    firstName: 'Marthena',
    lastName: 'Redmayne',
    email: 'mredmaynem@amazon.co.uk',
    salesTotal: '$12999.29',
    img: 'https://randomuser.me/api/portraits/women/47.jpg',
    verified: false,
    phoneNumber: '(345) 678-9012',
  },
  {
    id: 24,
    firstName: 'Felita',
    lastName: 'Borless',
    email: 'fborlessn@csmonitor.com',
    salesTotal: '$5732.01',
    img: 'https://randomuser.me/api/portraits/women/72.jpg',
    verified: true,
    phoneNumber: '(456) 789-0123',
  },
  {
    id: 25,
    firstName: 'Fitzgerald',
    lastName: 'Tupp',
    email: 'ftuppo@hubpages.com',
    salesTotal: '$7452.55',
    img: 'https://randomuser.me/api/portraits/men/36.jpg',
    verified: false,
    phoneNumber: '(567) 890-1234',
  },
  {
    id: 26,
    firstName: 'Mikaela',
    lastName: 'Schwerin',
    email: 'mschwerinp@jiathis.com',
    salesTotal: '$9471.05',
    img: 'https://randomuser.me/api/portraits/women/84.jpg',
    verified: true,
    phoneNumber: '(678) 901-2345',
  },
  {
    id: 27,
    firstName: 'Pris',
    lastName: 'Brabyn',
    email: 'pbrabynq@ycombinator.com',
    salesTotal: '$10843.62',
    img: 'https://randomuser.me/api/portraits/women/94.jpg',
    verified: false,
    phoneNumber: '(789) 012-3456',
  },
  {
    id: 28,
    firstName: 'Abramo',
    lastName: 'Longbone',
    email: 'alongboner@dailymail.co.uk',
    salesTotal: '$12102.60',
    img: 'https://randomuser.me/api/portraits/men/55.jpg',
    verified: true,
    phoneNumber: '(890) 123-4567',
  },
  {
    id: 29,
    firstName: 'Germaine',
    lastName: 'Blankhorn',
    email: 'gblankhorns@a8.net',
    salesTotal: '$7452.32',
    img: 'https://randomuser.me/api/portraits/men/91.jpg',
    verified: false,
    phoneNumber: '(901) 234-5678',
  },
  {
    id: 30,
    firstName: 'Kory',
    lastName: 'Frain',
    email: 'kfraint@sun.com',
    salesTotal: '$11340.96',
    img: 'https://randomuser.me/api/portraits/men/0.jpg',
    verified: true,
    phoneNumber: '(012) 345-6789',
  },
  {
    id: 31,
    firstName: 'Ulrika',
    lastName: 'Steane',
    email: 'usteaneu@vinaora.com',
    salesTotal: '$11966.48',
    img: 'https://randomuser.me/api/portraits/women/12.jpg',
    verified: false,
    phoneNumber: '(123) 456-7890',
  },
  {
    id: 32,
    firstName: 'Shandee',
    lastName: 'Robillard',
    email: 'srobillardv@scientificamerican.com',
    salesTotal: '$9417.07',
    img: 'https://randomuser.me/api/portraits/women/21.jpg',
    verified: true,
    phoneNumber: '(234) 567-8901',
  },
  {
    id: 33,
    firstName: 'Britte',
    lastName: 'Hurran',
    email: 'bhurranw@odnoklassniki.ru',
    salesTotal: '$12464.13',
    img: 'https://randomuser.me/api/portraits/women/73.jpg',
    verified: false,
    phoneNumber: '(345) 678-9012',
  },
  {
    id: 34,
    firstName: 'Lory',
    lastName: 'Peppard',
    email: 'lpeppardx@businessinsider.com',
    salesTotal: '$9334.81',
    img: 'https://randomuser.me/api/portraits/women/60.jpg',
    verified: true,
    phoneNumber: '(456) 789-0123',
  },
  {
    id: 35,
    firstName: 'Carmen',
    lastName: 'Sellars',
    email: 'csellarsy@seesaa.net',
    salesTotal: '$6731.71',
    img: 'https://randomuser.me/api/portraits/women/46.jpg',
    verified: false,
    phoneNumber: '(567) 890-1234',
  },
  {
    id: 36,
    firstName: 'Shir',
    lastName: 'Adkin',
    email: 'sadkinz@live.com',
    salesTotal: '$5924.65',
    img: 'https://randomuser.me/api/portraits/men/39.jpg',
    verified: true,
    phoneNumber: '(678) 901-2345',
  },
  {
    id: 37,
    firstName: 'Bert',
    lastName: 'Baudouin',
    email: 'bbaudouin10@seesaa.net',
    salesTotal: '$8723.98',
    img: 'https://randomuser.me/api/portraits/women/43.jpg',
    verified: false,
    phoneNumber: '(789) 012-3456',
  },
  {
    id: 38,
    firstName: 'Faythe',
    lastName: 'Staite',
    email: 'fstaite11@163.com',
    salesTotal: '$8987.16',
    img: 'https://randomuser.me/api/portraits/men/89.jpg',
    verified: true,
    phoneNumber: '(890) 123-4567',
  },
  {
    id: 39,
    firstName: 'Dimitry',
    lastName: 'Gribble',
    email: 'dgribble12@answers.com',
    salesTotal: '$6705.46',
    img: 'https://xsgames.co/randomusers/assets/avatars/male/5.jpg',
    verified: false,
    phoneNumber: '(901) 234-5678',
  },
  {
    id: 40,
    firstName: 'Allis',
    lastName: 'Mcmanaman',
    email: 'amcmanaman13@businessinsider.com',
    salesTotal: '$6062.15',
    img: 'https://xsgames.co/randomusers/assets/avatars/female/74.jpg',
    verified: true,
    phoneNumber: '(012) 345-6789',
  },
  {
    id: 41,
    firstName: 'Putnem',
    lastName: 'Mathy',
    email: 'pmathy14@howstuffworks.com',
    salesTotal: '$12569.04',
    img: 'https://xsgames.co/randomusers/assets/avatars/male/57.jpg',
    verified: true,
    phoneNumber: '(678) 901-2345',
  },
  {
    id: 42,
    firstName: 'Lemmie',
    lastName: 'Timmens',
    email: 'ltimmens15@barnesandnoble.com',
    salesTotal: '$5796.78',
    img: 'https://xsgames.co/randomusers/assets/avatars/male/6.jpg',
    verified: false,
    phoneNumber: '(789) 012-3456',
  },
  {
    id: 43,
    firstName: 'Silvia',
    lastName: 'Costall',
    email: 'scostall16@jugem.jp',
    salesTotal: '$8112.34',
    img: 'https://xsgames.co/randomusers/assets/avatars/female/22.jpg',
    verified: true,
    phoneNumber: '(890) 123-4567',
  },
  {
    id: 44,
    firstName: 'Ola',
    lastName: 'Blinder',
    email: 'oblinder17@bandcamp.com',
    salesTotal: '$8332.11',
    img: 'https://xsgames.co/randomusers/assets/avatars/female/69.jpg',
    verified: true,
    phoneNumber: '(901) 234-5678',
  },
  {
    id: 45,
    firstName: 'Vin',
    lastName: 'Adney',
    email: 'vadney18@csmonitor.com',
    salesTotal: '$8219.15',
    img: 'https://xsgames.co/randomusers/assets/avatars/male/37.jpg',
    verified: false,
    phoneNumber: '(012) 345-6789',
  },
  {
    id: 46,
    firstName: 'Wanids',
    lastName: 'Wilkinson',
    email: 'wwilkinson19@cnbc.com',
    salesTotal: '$7024.09',
    img: 'https://xsgames.co/randomusers/assets/avatars/female/5.jpg',
    verified: true,
    phoneNumber: '(123) 456-7890',
  },
  {
    id: 47,
    firstName: 'Kelsey',
    lastName: 'Bernardinelli',
    email: 'kbernardinelli1a@domainmarket.com',
    salesTotal: '$9112.02',
    img: 'https://xsgames.co/randomusers/assets/avatars/female/49.jpg',
    verified: false,
    phoneNumber: '(234) 567-8901',
  },
  {
    id: 48,
    firstName: 'Lucien',
    lastName: 'Kimbell',
    email: 'lkimbell1b@canalblog.com',
    salesTotal: '$10042.03',
    img: 'https://xsgames.co/randomusers/assets/avatars/male/46.jpg',
    verified: true,
    phoneNumber: '(345) 678-9012',
  },
  {
    id: 49,
    firstName: 'Staford',
    lastName: 'Melin',
    email: 'smelin1c@cargocollective.com',
    salesTotal: '$8824.90',
    img: 'https://xsgames.co/randomusers/assets/avatars/male/17.jpg',
    verified: true,
    phoneNumber: '(456) 789-0123',
  },
  {
    id: 50,
    firstName: 'Hannah',
    lastName: 'Braiden',
    email: 'hbraiden1d@plala.or.jp',
    salesTotal: '$8249.30',
    img: 'https://xsgames.co/randomusers/assets/avatars/female/71.jpg',
    verified: false,
    phoneNumber: '(567) 890-1234',
  },
  {
    id: 51,
    firstName: 'Sallyanne',
    lastName: 'Skin',
    email: 'sskin1e@is.gd',
    salesTotal: '$5787.27',
    img: 'https://xsgames.co/randomusers/assets/avatars/female/20.jpg',
    verified: true,
    phoneNumber: '(678) 901-2345',
  },
  {
    id: 52,
    firstName: 'Ker',
    lastName: 'Danieli',
    email: 'kdanieli1f@simplemachines.org',
    salesTotal: '$12693.46',
    img: 'https://xsgames.co/randomusers/assets/avatars/male/42.jpg',
    verified: true,
    phoneNumber: '(789) 012-3456',
  },
  {
    id: 53,
    firstName: 'Denny',
    lastName: 'Hazelden',
    email: 'dhazelden1g@surveymonkey.com',
    salesTotal: '$6004.92',
    img: 'https://xsgames.co/randomusers/assets/avatars/male/4.jpg',
    verified: false,
    phoneNumber: '(890) 123-4567',
  },
  {
    id: 54,
    firstName: 'Cecilia',
    lastName: 'Sheach',
    email: 'csheach1h@trellian.com',
    salesTotal: '$6673.67',
    img: 'https://xsgames.co/randomusers/assets/avatars/female/7.jpg',
    verified: true,
    phoneNumber: '(901) 234-5678',
  },
  {
    id: 55,
    firstName: 'Dallis',
    lastName: 'Loftus',
    email: 'dloftus1i@arstechnica.com',
    salesTotal: '$10555.75',
    img: 'https://xsgames.co/randomusers/assets/avatars/female/62.jpg',
    verified: true,
    phoneNumber: '(012) 345-6789',
  },
  {
    id: 56,
    firstName: 'Andriana',
    lastName: 'Gourlay',
    email: 'agourlay1j@vkontakte.ru',
    salesTotal: '$8156.03',
    img: 'https://xsgames.co/randomusers/assets/avatars/female/27.jpg',
    verified: false,
    phoneNumber: '(123) 456-7890',
  },
  {
    id: 57,
    firstName: 'Bert',
    lastName: 'Seville',
    email: 'bseville1k@amazon.co.jp',
    salesTotal: '$11110.20',
    img: 'https://xsgames.co/randomusers/assets/avatars/male/23.jpg',
    verified: true,
    phoneNumber: '(234) 567-8901',
  },
  {
    id: 58,
    firstName: 'Isadore',
    lastName: 'Eskrigge',
    email: 'ieskrigge1l@dion.ne.jp',
    salesTotal: '$12145.49',
    img: 'https://xsgames.co/randomusers/assets/avatars/female/66.jpg',
    verified: false,
    phoneNumber: '(345) 678-9012',
  },
  {
    id: 59,
    firstName: 'Sheena',
    lastName: 'Tomei',
    email: 'stomei1m@gizmodo.com',
    salesTotal: '$8774.84',
    img: 'https://xsgames.co/randomusers/assets/avatars/female/35.jpg',
    verified: true,
    phoneNumber: '(456) 789-0123',
  },
  {
    id: 60,
    firstName: 'Clemence',
    lastName: 'Gentreau',
    email: 'cgentreau1n@tripadvisor.com',
    salesTotal: '$12311.77',
    img: 'https://xsgames.co/randomusers/assets/avatars/male/22.jpg',
    verified: false,
    phoneNumber: '(567) 890-1234',
  },
  {
    id: 61,
    firstName: 'Dunc',
    lastName: 'Olivas',
    email: 'dolivas1o@japanpost.jp',
    salesTotal: '$13196.43',
    img: 'https://xsgames.co/randomusers/assets/avatars/male/3.jpg',
    verified: true,
    phoneNumber: '(678) 901-2345',
  },
  {
    id: 62,
    firstName: 'Enrico',
    lastName: 'Kirimaa',
    email: 'ekirimaa1p@gravatar.com',
    salesTotal: '$13120.97',
    img: 'https://xsgames.co/randomusers/assets/avatars/male/74.jpg',
    verified: false,
    phoneNumber: '(789) 012-3456',
  },
  {
    id: 63,
    firstName: 'Cory',
    lastName: 'McKechnie',
    email: 'cmckechnie1q@csmonitor.com',
    salesTotal: '$9719.11',
    img: 'https://xsgames.co/randomusers/assets/avatars/male/30.jpg',
    verified: true,
    phoneNumber: '(890) 123-4567',
  },
  {
    id: 64,
    firstName: 'Chaddie',
    lastName: 'Pawley',
    email: 'cpawley1r@hugedomains.com',
    salesTotal: '$11939.82',
    img: 'https://xsgames.co/randomusers/assets/avatars/female/41.jpg',
    verified: true,
    phoneNumber: '(901) 234-5678',
  },
  {
    id: 65,
    firstName: 'Vasily',
    lastName: 'Burrus',
    email: 'vburrus1s@google.com.br',
    salesTotal: '$8396.84',
    img: 'https://xsgames.co/randomusers/assets/avatars/female/67.jpg',
    verified: false,
    phoneNumber: '(012) 345-6789',
  },
];
